# knowledge base.py

knowledge_base = {
    "facts": {
        "sad": False,
        "low": False,
        "hopeless": False,
        "helpless": False,
        "tearful": False,
        "lack of interest": False,
        "anxious": False,
        "fatigue": False,
        "difficulties in life": False,
        "trouble sleeping": False,
        "feeling nervous": False,
        "worrying": False,
        "irritated": False,
        "trouble concentrating": False,
        "feeling overwhelmed": False,
        "uncontrollable worry": False,
        "flashbacks": False,
        "nightmares": False,
        "guilty": False,
        "obsessions": False,
        "fear harming others": False,
        "fear accidental harm": False,
        "fear contamination": False,
        "need symmetry order": False,
        "disturbing thoughts": False,
        "compulsive cleaning": False,
        "compulsive checking": False,
        "compulsive counting": False,
        "arranging items": False,
        "seeking reassurance": False,
        "repetitive actions": False,
        "avoidance behavior": False,
        "panicing": False,
        "panic attack": False,
        "sweating": False,
        "racing heartbeat": False,
        "chills": False,
        "nausea": False,
        "shaky limbs": False,
        "dizziness": False,
        "shortness of breath": False,
        "pins and needles": False,
        "lasts up to 20 minutes": False,
        "hallucinations": False,
        "delusions": False,
        "paranoia": False,
        "hearing voices": False,
        "seeing things": False,
        "smelling things": False,
        "feeling controlled": False,
        "avoiding people": False,
        "lack of self care": False,
        "mood swings": False,
        "sudden mood change": False,
        "increased energy": False,
        "easily annoyed": False,
        "excessive spending": False,
        "decreased need for sleep or food": False,
        "body dysmorphia": False,
        "worrying about body": False,
        "worrying about weight": False,
        "eating less": False,
        "restricting food": False,
        "exercising excessively": False,
        "numbness in arms and legs": False,
        "digestive issue diarhhea": False,
        "diarhhea": False,
        "higher weight": False,
        "lower weight": False,
        "delayed period": False,
        "carelessness": False,
        "difficulty finishing tasks": False,
        "poor organizational skills": False,
        "difficulty focusing": False,
        "losing items": False,
        "forgetfulness": False,
        "restlessness": False,
        "difficulty staying quiet": False,
        "speaking out of turn": False,
        "interrupting others": False,
        "quick temper": False,
        "inability to handle stress": False,
        "impatience": False,
        "taking risks": False,
        "easily offended": False,
        "defensive": False,
        "aggression": False,
        "inability to compromise": False,
        "struggling with criticism": False,
        "feeling false touches": False,
        "rapid or constantspeech": False,
        "switching topics mid sentence": False,
        "persecutory delusions": False,
        "grandiose delusions": False,
        "emotional instability": False,
        "intense negative emotions": False,
        "rage": False,
        "sorrow": False,
        "cognitive distortions": False,
        "perceptual distortions": False,
        "impulsive actions": False,
        "reckless behavior": False,
        "fear of abandonment": False,
        "idealization devaluation": False,
        "perceived threats": False,
        "delusion": False
    },
    "rules": [
        {
            "if": {
                "sad": True,
                "low": True,
                "hopeless": True,
                "helpless": True,
                "tearful": True,
                "lack of interest": True,
                "anxious": True,
                "fatigue": True,
                "difficulties in life": True,
                "trouble sleeping": True
            },
            "then": "depression"
        },
        {
            "if": {
                "anxious": True,
                "feeling nervous": True,
                "worrying": True,
                "irritated": True,
                "trouble concentrating": True,
                "feeling overwhelmed": True,
                "uncontrollable worry": True,
                "trouble sleeping": True,
                "fatigue": True
            },
            "then": "general anxiety"
        },
        {
            "if": {
                "flashbacks": True,
                "nightmares": True,
                "irritated": True,
                "guilty": True,
                "trouble concentrating": True,
                "trouble sleeping": True
            },
            "then": "ptsd"
        },
        {
            "if": {
                "obsessions": True,
                "fear harming others": True,
                "fear accidental harm": True,
                "fear contamination": True,
                "need symmetry order": True,
                "disturbing thoughts": True,
                "compulsive cleaning": True,
                "compulsive checking": True,
                "compulsive counting": True,
                "arranging items": True,
                "seeking reassurance": True,
                "repetitive actions": True,
                "avoidance behavior": True,
                "anxious": True
            },
            "then": "ocd"
        },
        {
            "if": {
                "anxious": True,
                "worrying": True,
                "panicing": True,
                "panic attack": True,
                "sweating": True,
                "racing heartbeat": True,
                "chills": True,
                "nausea": True,
                "shaky limbs": True,
                "dizziness": True,
                "shortness of breath": True,
                "pins and needles": True,
                "lasts up to 20 minutes": True
            },
            "then": "panic disorder"
        },
        {
            "if": {
                "hallucinations": True,
                "delusions": True,
                "delusion": True,
                "paranoia": True,
                "hearing voices": True,
                "seeing things": True,
                "smelling things": True,
                "trouble concentrating": True,
                "feeling controlled": True,
                "avoiding people": True,
                "lack of self care": True
            },
            "then": "schizophrenia"
        },
        {
            "if": {
                "mood swings": True,
                "sudden mood change": True,
                "sad": True,
                "low": True,
                "trouble concentrating": True,
                "lack of interest": True,
                "increased energy": True,
                "easily annoyed": True,
                "excessive spending": True,
                "decreased need for sleep or food": True,
                "delusions": True,
                "hallucinations": True,
                "irritated": True
            },
            "then": "bipolar disorder"
        },
        {
            "if": {
                "body dysmorphia": True,
                "worrying about body": True,
                "worrying about weight": True,
                "avoiding people": True,
                "eating less": True,
                "restricting food": True,
                "anxious": True,
                "exercising excessively": True,
                "dizziness": True,
                "numbness in arms and legs": True,
                "digestive issue diarhhea": True,
                "diarhhea": True,
                "higher weight": True,
                "lower weight": True,
                "delayed period": True
            },
            "then": "eating disorder"
        },
        {
            "if": {
                "mood swings": True,
                "carelessness": True,
                "difficulty finishing tasks": True,
                "poor organizational skills": True,
                "difficulty focusing": True,
                "losing items": True,
                "forgetfulness": True,
                "restlessness": True,
                "difficulty staying quiet": True,
                "speaking out of turn": True,
                "interrupting others": True,
                "quick temper": True,
                "inability to handle stress": True,
                "impatience": True,
                "taking risks": True
            },
            "then": "adhd"
        },
        {
            "if": {
                "emotional instability": True,
                "intense negative emotions": True,
                "rage": True,
                "sorrow": True,
                "mood swings": True,
                "cognitive distortions": True,
                "perceptual distortions": True,
                "impulsive actions": True,
                "reckless behavior": True,
                "fear of abandonment": True,
                "idealization devaluation": True
            },
            "then": "borderline personality disorder"
        },
        {
            "if": {
                "emotional instability": True,
                "delusions": True,
                "hallucinations": True,
                "feeling controlled": True,
                "perceived threats": True,
                "easily offended": True,
                "defensive": True,
                "aggression": True,
                "inability to compromise": True,
                "struggling with criticism": True
            },
            "then": "paranoia"
        },
        {
            "if": {
                "hallucinations": True,
                "seeing things": True,
                "feeling false touches": True,
                "hearing voices": True,
                "delusions": True,
                "rapid or constant speech": True,
                "switching topics mid sentence": True,
                "persecutory delusions": True,
                "grandiose delusions": True
            },
            "then": "psychosis"
        }
    ]
}

